pluginManagement {
    repositories {
        maven { url "https://maven.fabricmc.net/" }
        maven { url "https://maven.architectury.dev/" }
        maven { url "https://files.minecraftforge.net/maven/" }
        maven {
            name = 'ParchmentMC'
            url = 'https://maven.parchmentmc.org'
        }
        gradlePluginPortal()
    }
}

rootProject.name = 'sdmrecipemachinestages'

include 'common'
// This fork uses AStages, which is available on NeoForge for Minecraft 1.21.1.
include 'neoforge'
